version: '3.3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      NODE_ENV: development
      PGUSER: thor
      PGHOST: postgres
      PGPASSWORD: thor
      PGDATABASE: thorcommerce
      PGPORT: 5432
      DATABASE_URL: postgres://thor:thor@postgres:5432/thorcommerce
      ACCESS_TOKEN_SECRET_KEY: 12@!2389das0123masdm123
      REFRESH_TOKEN_SECRET_KEY: 1%1cawsA%^&asldkop9!!
    depends_on:
      - postgres
  
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: thor
      POSTGRES_PASSWORD: thor
      POSTGRES_DB: thorcommerce
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
